on:
  pull_request:
    paths:
    - app/**
  push:
    paths:
    - app/**
    branches:         # array of glob patterns matching against refs/heads. Optional; defaults to all
    - master          # triggers on pushes that contain changes in master
jobs:
  build:
    name: Build the image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Build and tag the image
      run: |
        # Build and tag the image
        docker build \
          -t app:v1
    - name: Snyk Container Test
      continue-on-error: true
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ Secrets.SNYK_TOKEN }}
      with:
        image: app:v1
        args: --file=Dockerfile
  
